/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "suma.h"

bool_t
xdr_sumandos(XDR *xdrs, sumandos *objp)
{

	if (!xdr_int(xdrs, &objp->num))
		return (FALSE);
	return (TRUE);
}
