/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUMA_H_RPCGEN
#define _SUMA_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct sumandos {
	int num;
};
typedef struct sumandos sumandos;
#ifdef __cplusplus
extern "C" bool_t xdr_sumandos(XDR *, sumandos*);
#elif __STDC__
extern  bool_t xdr_sumandos(XDR *, sumandos*);
#else /* Old Style C */
bool_t xdr_sumandos();
#endif /* Old Style C */


#define PROGRAMA_SUMA ((rpc_uint)0x20000001)
#define VERSION_SUMA ((rpc_uint)1)

#ifdef __cplusplus
#define suma ((rpc_uint)1)
extern "C" int * suma_1(sumandos *, CLIENT *);
extern "C" int * suma_1_svc(sumandos *, struct svc_req *);

#elif __STDC__
#define suma ((rpc_uint)1)
extern  int * suma_1(sumandos *, CLIENT *);
extern  int * suma_1_svc(sumandos *, struct svc_req *);

#else /* Old Style C */
#define suma ((rpc_uint)1)
extern  int * suma_1();
extern  int * suma_1_svc();
#endif /* Old Style C */

#endif /* !_SUMA_H_RPCGEN */
