/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "suma.h"

char **
suma_1_svc(sumandos *argp, struct svc_req *rqstp)
{

	static char * result[1024];
	srand(time(NULL));
	/*
	 * insert server code here
	 */
	printf("Server running...\n");
	int LEN = argp->num;
	int i=0,j=0;
	printf("Creare una matriz %dx%d  \n", LEN, LEN);
	//MATRICES DINAMICAS
	int **M,**N,**R;
	//RESERVACION DE ESPACOS EN FILAS
	M = (int **)malloc (LEN*sizeof(int *));
	N = (int **)malloc (LEN*sizeof(int *));
	R = (int **)malloc (LEN*sizeof(int *));
	//RESERVACION DE ESPACOS EN COLUMNAS
	for (i=0;i<LEN;i++) {
		M[i] = (int *) malloc (LEN*sizeof(int));
		N[i] = (int *) malloc (LEN*sizeof(int));
		R[i] = (int *) malloc (LEN*sizeof(int));
	}
	char letras[1000];
	char caracLen[100];
	sprintf(caracLen,"%d",LEN);
	int lenDig = strlen(caracLen);
	printf("%d Son los digitos\n", lenDig);
	strcpy(letras,"");
	//CALCULO y RESULTADO
		result[0] = (char *) malloc ((((LEN*LEN)*lenDig)+LEN)*sizeof(char));
	for (i = 0; i < LEN; i++)
	{
		for (j = 0; j < LEN; j++)
		{
		  M[i][j] = rand() % LEN;
		  N[i][j] = rand() % LEN;
		  R[i][j] = M[i][j] + N[i][j];
		  printf("%d ", R[i][j]);
		  /*char dig[lenDig*2];
		  sprintf(dig,"%d",R[i][j]);
		  strcat(letras, dig);
		  strcat(letras, " ");*/
		  asprintf(&result, "%s %d", result[0], R[i][j]);
		}
		asprintf(&result, "%s\n", result[0]);
		printf("\n");
	}
	/*
		for (i = 0; i < 2; i++)
		{
			for (j = 0; i < 2; j++)
			{
			 printf("%d ", M[i][j]);
			}
			printf("\n");
		}*/
	free(M);
	free(N);
	free(R);
	return(&result);
}
